spring:
# 数据库
  datasource:
    username: root
    password: piu_piu
    url: jdbc:mysql://47.94.237.163:3306/piu?useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
#   数据源其他配置
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
#   配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: [stat,wall,log4j]
    maxPoolPreparedStatementPerConnectionSize: 20
    useGlobalDataSourceStat: true
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
#   事务配置
  transaction:
    rollback-on-commit-failure: true
    default-timeout: 1500
  thymeleaf:
    cache: false
  mail:
    default-encoding: UTF-8
    host: smtp.163.com
    username: m13935385051@163.com
    password: wd654321
    port: 465
    protocol: smtp
    properties:
      mail.smtp.starttls.enable : true
      mail.smtp.auth : true
      mail.smtp.socketFactory.class : javax.net.ssl.SSLSocketFactory
    #jndi-name: mail / Session
  servlet:
    multipart:
      max-file-size: 100Mb
      max-request-size: 100Mb
mybatis:
  # 指定全局配置文件位置
  config-location: classpath:mybatis-config.xml
  # 指定sql映射文件位置
  mapper-locations: classpath:mapper/*/*Dao.xml
  # model 实体类
  type-aliases-package: com.piu.*.entity
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql
#mapper:
#  mappers:
#    - tk.mybatis.springboot.util.MyMapper
#  not-empty: false
#  identity: MYSQL
server:
  port: 80
  #servlet:
   # context-path: /piu
